version: '3'

services:
  ecommerce:
    container_name: ecommerce
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - ecommerce-db
      - ecommerce-redis
    volumes:
      - ecommerce_media:/media
      - ecommerce_static:/static
    command: /start-django
    expose:
      - 8000
    ports:
      - "9000:8000"

  ecommerce-db:
    container_name: ecommerce-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - ecommerce_db_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
  
  ecommerce-redis:
    container_name: ecommerce-redis
    image: redis:7
    ports:
      - "6738:6739"


volumes:
  ecommerce_db_data: {}
  ecommerce_media: {}
  ecommerce_static: {}